In [17]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv("email.csv")

In [19]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [20]:
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [21]:
df.shape

(5572, 2)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [23]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [24]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [25]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [29]:
X_train.shape

(4457,)

In [30]:
X_test.shape

(1115,)

In [31]:
type(X_train)

pandas.core.series.Series

In [34]:
X_train[:4]

3036    Raji..pls do me a favour. Pls convey my Birthd...
1795                     How much i gave to you. Morning.
4221    U free on sat rite? U wan 2 watch infernal aff...
1370                     Did you try making another butt.
Name: Message, dtype: object

In [35]:
X_train[:4][3036]

'Raji..pls do me a favour. Pls convey my Birthday wishes to Nimya. Pls. Today is her birthday.'

In [36]:
y_train.shape

(4457,)

In [37]:
type(y_train)

pandas.core.series.Series

In [38]:
y_train[:4]

3036    0
1795    0
4221    0
1370    0
Name: spam, dtype: int64

In [39]:
type(X_train.values)

numpy.ndarray

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
v = CountVectorizer()

In [42]:
x_train = v.fit_transform(X_train.values)
x_train

<4457x7648 sparse matrix of type '<class 'numpy.int64'>'
	with 59132 stored elements in Compressed Sparse Row format>

In [44]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [45]:
x_train.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
x_train.shape

(4457, 7648)

In [47]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [49]:
v.get_feature_names_out()[90:140]

array(['0870737910216yrs', '08707500020', '08707509020', '0870753331018',
       '08707808226', '08708034412', '08708800282', '08709222922',
       '08709501522', '0871', '087104711148', '08712101358',
       '08712300220', '087123002209am', '08712317606', '08712400200',
       '08712400602450p', '08712402050', '08712402578', '08712402902',
       '08712402972', '08712404000', '08712405020', '08712405022',
       '08712460324', '0871277810710p', '0871277810810', '0871277810910p',
       '08714342399', '087147123779am', '08714712388', '08714712394',
       '08714712412', '08715203656', '08715203677', '08715203694',
       '08715205273', '08715705022', '08717111821', '08717168528',
       '0871750', '08717507382', '08717509990', '08717890890',
       '08717895698', '08717898035', '08718711108', '08718720201',
       '08718725756', '08718726270'], dtype=object)

In [50]:
v.get_feature_names_out().shape

(7648,)

In [51]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [54]:
v.vocabulary_

{'raji': 5498,
 'pls': 5202,
 'do': 2349,
 'me': 4348,
 'favour': 2763,
 'convey': 1982,
 'my': 4611,
 'birthday': 1364,
 'wishes': 7449,
 'to': 6864,
 'nimya': 4729,
 'today': 6870,
 'is': 3704,
 'her': 3377,
 'how': 3486,
 'much': 4580,
 'gave': 3056,
 'you': 7606,
 'morning': 4534,
 'free': 2954,
 'on': 4879,
 'sat': 5845,
 'rite': 5739,
 'wan': 7285,
 'watch': 7310,
 'infernal': 3632,
 'affairs': 851,
 'wif': 7419,
 'darren': 2145,
 'mayb': 4341,
 'xy': 7567,
 'did': 2277,
 'try': 6983,
 'making': 4272,
 'another': 985,
 'butt': 1573,
 'only': 4889,
 'send': 5943,
 'the': 6747,
 'contents': 1971,
 'page': 4988,
 'arun': 1092,
 'can': 1628,
 'transfr': 6946,
 'amt': 959,
 'wherre': 7397,
 'boytoy': 1473,
 'sounds': 6281,
 'good': 3155,
 'keep': 3860,
 'posted': 5273,
 'its': 3720,
 'just': 3827,
 'effect': 2511,
 'of': 4839,
 'irritation': 3702,
 'ignore': 3572,
 'it': 3715,
 'if': 3568,
 'die': 2281,
 'want': 7289,
 'have': 3321,
 'all': 915,
 'stuffs': 6479,
 'winner': 7441,
 'as'

In [55]:
len(v.vocabulary_)

7648

In [56]:
v.get_feature_names_out()[2349]

'do'

In [57]:
x_train_np = x_train.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
x_train_np[5:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [61]:
x_train_np[5:10][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [62]:
np.where(x_train_np[5]!=0)

(array([ 959, 1092, 1628, 4348, 6946], dtype=int64),)

**The Bag-of-Words model is a simple yet effective technique for representing text documents as numerical vectors. It involves counting the occurrences of each word in a document and representing the document as a vector of these counts.

#### Advantages:

- Simplicity: It's easy to understand and implement.
- Versatility: It can be used for various NLP tasks like text classification, sentiment analysis, and topic modeling.
- Efficiency: BoW models are computationally efficient, especially for large datasets.

#### Disadvantages:

- Loss of Semantic Information: BoW models ignore the order of words and their semantic relationships. This can lead to the loss of important information, especially for tasks that rely on context.
- High Dimensionality: As the vocabulary size increases, the dimensionality of the feature space also increases, leading to sparse vectors. This can negatively impact model performance and computational efficiency.
- Sensitivity to Stop Words: Stop words (common words like "the," "and," "of") can contribute to noise and can be detrimental to model performance.
- Lack of Contextual Understanding: BoW models cannot capture the nuances of language, such as polysemy (words with multiple meanings) and synonymy (words with similar meanings).